sonar.projectKey=COG-GTM_etl-pipeline-demo
sonar.organization=cog-gtm
sonar.python.version=3.8

sonar.sources=src,main.py,demo
sonar.exclusions=**/__pycache__/**,**/node_modules/**,**/*.pyc

sonar.host.url=https://sonarcloud.io
